---
title: "Utah Car Accidents Data and Code"
author: "Kenneth Pomeyie, Scout Jarman, Paul Gaona-Partida"
output:
  pdf_document: default
---
### Load Libraries and Data file
```{r}
# For Data Cleaning and Visualization
library("dplyr")
library("tigris")
library("ggplot2")
library("sf")

crash <- read.csv("../data-raw/RawCrashData2020.csv")
stations <- read.csv("../data-raw/i_15_Flow_Data_2020.csv")
```



### Data Prepping

## Car Accidents

```{r}
# subset to retain only potentially useful information
# Route: I-15 Highway route
# milepoint: Milepoint of accident
# Coords: Lat and Long

crash_i15 <- crash %>%
  dplyr::filter(Route == "0015") %>%
  dplyr::select(.,Lat, Long)

```

```{r}
# Basic plot of points of accidents
ggplot() +
  geom_point(
    data = crash_i15,
    aes(x = Long, y = Lat)
  )
```

```{r}
# Sf with NAD83 matches CRS of Utah map and Roads
i15_spat <- sf::st_as_sf(
  x = crash_i15,
  coords = c("Long", "Lat"),
  crs = 4269
)
```

```{r}
# Plot of spatial object crashes
crash_plot <- ggplot(i15_spat) +
  geom_sf()
crash_plot
```



## Roads

https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2020/TGRSHP2020_TechDoc.pdf

Link: Census.gob information on Tigris shapefiles

Important: Original CRS = NAD83

```{r}
# subset of Interstates in Utah
roads <- tigris::primary_secondary_roads("Utah") %>%
  dplyr::filter(RTTYP %in% c("I"))
```

```{r}
# plot of ALL Interstates in Utah (Utah not fitted)
ggplot() +
  geom_sf(
    data = roads,
    color = "blue",
    aes(geometry = geometry)
  )
```

```{r}
# subset of I-15 and convert to MultiLineString
roads_i15 <- roads[which(roads$FULLNAME == "I- 15"), ] %>%
  sf::st_cast(., "MULTILINESTRING")
```

```{r}
# plot of i-15 in Utah (Interstate only)
road_plot <- ggplot() +
  geom_sf(
    data = roads_i15,
    color = "blue",
    aes(geometry = geometry)
  )
road_plot
```



## Utah


```{r}
# sf of USA
us_geo <- tigris::states(class = "sf", cb = TRUE) %>%
  shift_geometry()
```

```{r}
# Subsetting to Utah and changing crs to match roads in Utah
ut_map <- us_geo[which(us_geo$NAME == "Utah"), ] %>%
  st_transform(., crs = st_crs(roads_i15))
```

```{r}
# plot of Utah
ut_plot <- ggplot(ut_map) +
  geom_sf()
ut_plot
```

```{r}
# plot of Stations
ggplot() +
  geom_point(
    data = stations,
    aes(x = Longitude, y = Latitude)
  )
```

```{r}
# Sf with NAD83 matches CRS of Utah map and Roads
stat_spat <- sf::st_as_sf(
  x = stations,
  coords = c("Longitude", "Latitude"),
  crs = 4269
)
```

```{r}
# Plot of spatial object crashes
station_plot <- ggplot(stat_spat) +
  geom_sf(shape = 3)
station_plot
```

```{r}
# plot of Utah, I-15, and Car Accidents
all_plot <- ggplot(ut_map) +
  geom_sf(fill = NA) +
  geom_sf(
    data = roads_i15,
    color = "red"
  ) +
  geom_sf(
    data = i15_spat,
    color = "blue",
    alpha = 0.025
  ) +
  geom_sf(
    data = stat_spat,
          shape = 3,
    color = "yellow"
    )
all_plot
```

```{r}
# car crashes and stations
ggplot()+
  geom_sf(
    data = i15_spat,
    color = "blue",
    alpha = 0.025
  ) +
  geom_sf(
    data = stat_spat,
          shape = 3,
    color = "yellow"
    )
```

```{r}
library(ggmap)

tbbox <- sf::st_bbox(ut_map)
names(tbbox) <- c("left", "bottom", "right", "top")
samp_map <- ggmap::get_map(location = tbbox,
                           maptype = "terrain",
                           source = "google"
)
# map is slightly off 
ggmap(samp_map) +
  geom_sf(
    data = roads_i15,
    inherit.aes = F,
    color = "red"
  ) +
  geom_sf(
    data = i15_spat,
    inherit.aes = F,
    color = "blue",
    alpha = 0.025
  ) +
  geom_sf(
    data = stat_spat,
    inherit.aes = F,
    shape = 3,
    color = "yellow",
  )
  
roads_3857 <- sf::st_transform(roads_i15,3857)
crash_3857 <- sf::st_transform(i15_spat,3857)
station_3857 <- sf::st_transform(stat_spat,3857)

ggmapbbox <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}

# final map
samp_map2 <- ggmapbbox(samp_map)

ggmap(samp_map2) +
  geom_sf(
    data = roads_3857,
    inherit.aes = FALSE,
    fill = NA,
    lwd = 1,
    color = "red"
  ) +
  geom_sf(
    data = crash_3857,
    inherit.aes = FALSE,
    color = "blue",
    alpha = 0.05
    ) +
  geom_sf(
    data = station_3857,
    inherit.aes = FALSE,
    shape = 3,
    color = "yellow",
    lwd = .75,
  )
```

```{r}
#save code

#roads_i15
#i15_spat
#stat_spat

save(roads_i15, file = "../data-raw/RObject/roads_i15")
save(i15_spat, file = "../data-raw/RObject/i15_spat")
save(stat_spat, file = "../data-raw/RObject/stat_spat")
```